// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Skindexer.Api.Data;

#nullable disable

namespace Skindexer.Api.Migrations
{
    [DbContext(typeof(SkindexerDbContext))]
    partial class SkindexerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Skindexer.Api.Data.Entities.CollectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("game_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_collections");

                    b.HasIndex("GameId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_collections_game_id_slug");

                    b.ToTable("collections", (string)null);
                });

            modelBuilder.Entity("Skindexer.Api.Data.Entities.GradeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("game_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_grades");

                    b.HasIndex("GameId", "Order")
                        .IsUnique()
                        .HasDatabaseName("ix_grades_game_id_order");

                    b.HasIndex("GameId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_grades_game_id_slug");

                    b.ToTable("grades", (string)null);
                });

            modelBuilder.Entity("Skindexer.Api.Data.Entities.SkinItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AddedToGameAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_to_game_at");

                    b.Property<Guid?>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("game_id");

                    b.Property<Guid?>("GradeId")
                        .HasColumnType("uuid")
                        .HasColumnName("grade_id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsMarketable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_marketable");

                    b.Property<bool>("IsTradeable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_tradeable");

                    b.Property<Dictionary<string, object>>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_items");

                    b.HasIndex("CollectionId")
                        .HasDatabaseName("ix_items_collection_id");

                    b.HasIndex("GradeId")
                        .HasDatabaseName("ix_items_grade_id");

                    b.HasIndex("GameId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_items_game_id_slug");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("Skindexer.Api.Data.Entities.SkinPriceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("currency");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("price");

                    b.Property<string>("PriceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("price_type");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("slug");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source");

                    b.Property<int?>("Volume")
                        .HasColumnType("integer")
                        .HasColumnName("volume");

                    b.HasKey("Id")
                        .HasName("pk_price_snapshots");

                    b.HasIndex("ItemId", "RecordedAt")
                        .HasDatabaseName("ix_price_snapshots_item_id_recorded_at");

                    b.ToTable("price_snapshots", (string)null);
                });

            modelBuilder.Entity("Skindexer.Api.Data.Entities.SkinItemEntity", b =>
                {
                    b.HasOne("Skindexer.Api.Data.Entities.CollectionEntity", "Collection")
                        .WithMany("Items")
                        .HasForeignKey("CollectionId")
                        .HasConstraintName("fk_items_collections_collection_id");

                    b.HasOne("Skindexer.Api.Data.Entities.GradeEntity", "Grade")
                        .WithMany("Items")
                        .HasForeignKey("GradeId")
                        .HasConstraintName("fk_items_grades_grade_id");

                    b.Navigation("Collection");

                    b.Navigation("Grade");
                });

            modelBuilder.Entity("Skindexer.Api.Data.Entities.SkinPriceEntity", b =>
                {
                    b.HasOne("Skindexer.Api.Data.Entities.SkinItemEntity", "Item")
                        .WithMany("Prices")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_price_snapshots_items_item_id");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Skindexer.Api.Data.Entities.CollectionEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Skindexer.Api.Data.Entities.GradeEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Skindexer.Api.Data.Entities.SkinItemEntity", b =>
                {
                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
