// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Skindexer.Api.Data;

#nullable disable

namespace Skindexer.Api.Migrations
{
    [DbContext(typeof(SkindexerDbContext))]
    partial class SkindexerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Skindexer.Api.Data.Entities.CollectionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("game_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("slug");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_collections");

                    b.HasIndex("GameId", "Type", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_collections_game_id_type_slug");

                    b.ToTable("collections", (string)null);
                });

            modelBuilder.Entity("Skindexer.Api.Data.Entities.RarityEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<int?>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("order");

                    b.Property<Guid>("RarityGroupId")
                        .HasColumnType("uuid")
                        .HasColumnName("rarity_group_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_rarities");

                    b.HasIndex("RarityGroupId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_rarities_rarity_group_id_slug");

                    b.ToTable("rarities", (string)null);
                });

            modelBuilder.Entity("Skindexer.Api.Data.Entities.RarityGroupEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("game_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("slug");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_rarity_groups");

                    b.HasIndex("GameId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_rarity_groups_game_id_slug");

                    b.HasIndex("GameId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ix_rarity_groups_game_id_type");

                    b.ToTable("rarity_groups", (string)null);
                });

            modelBuilder.Entity("Skindexer.Api.Data.Entities.SkinItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("AddedToGameAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_to_game_at");

                    b.Property<Guid?>("CollectionId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("game_id");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsMarketable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_marketable");

                    b.Property<bool>("IsTradeable")
                        .HasColumnType("boolean")
                        .HasColumnName("is_tradeable");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("item_type");

                    b.Property<Dictionary<string, object>>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<Guid?>("RarityId")
                        .HasColumnType("uuid")
                        .HasColumnName("rarity_id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_items");

                    b.HasIndex("CollectionId")
                        .HasDatabaseName("ix_items_collection_id");

                    b.HasIndex("RarityId")
                        .HasDatabaseName("ix_items_rarity_id");

                    b.HasIndex("GameId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_items_game_id_slug");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("Skindexer.Api.Data.Entities.SkinPriceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("currency");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 8)
                        .HasColumnType("numeric(18,8)")
                        .HasColumnName("price");

                    b.Property<string>("PriceType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("price_type");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("slug");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("source");

                    b.Property<Guid>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.Property<int?>("Volume")
                        .HasColumnType("integer")
                        .HasColumnName("volume");

                    b.HasKey("Id")
                        .HasName("pk_price_snapshots");

                    b.HasIndex("VariantId", "Source", "PriceType", "RecordedAt")
                        .IsUnique()
                        .HasDatabaseName("ix_price_snapshots_variant_id_source_price_type_recorded_at");

                    b.ToTable("price_snapshots", (string)null);
                });

            modelBuilder.Entity("Skindexer.Api.Data.Entities.SkinVariantEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("GameId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("game_id");

                    b.Property<Guid>("ItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("item_id");

                    b.Property<Dictionary<string, object>>("Metadata")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_variants");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("ix_variants_item_id");

                    b.HasIndex("GameId", "Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_variants_game_id_slug");

                    b.ToTable("variants", (string)null);
                });

            modelBuilder.Entity("Skindexer.Api.Data.Entities.RarityEntity", b =>
                {
                    b.HasOne("Skindexer.Api.Data.Entities.RarityGroupEntity", "RarityGroup")
                        .WithMany("Rarities")
                        .HasForeignKey("RarityGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_rarities_rarity_groups_rarity_group_id");

                    b.Navigation("RarityGroup");
                });

            modelBuilder.Entity("Skindexer.Api.Data.Entities.SkinItemEntity", b =>
                {
                    b.HasOne("Skindexer.Api.Data.Entities.CollectionEntity", "Collection")
                        .WithMany("Items")
                        .HasForeignKey("CollectionId")
                        .HasConstraintName("fk_items_collections_collection_id");

                    b.HasOne("Skindexer.Api.Data.Entities.RarityEntity", "Rarity")
                        .WithMany("Items")
                        .HasForeignKey("RarityId")
                        .HasConstraintName("fk_items_rarities_rarity_id");

                    b.Navigation("Collection");

                    b.Navigation("Rarity");
                });

            modelBuilder.Entity("Skindexer.Api.Data.Entities.SkinPriceEntity", b =>
                {
                    b.HasOne("Skindexer.Api.Data.Entities.SkinVariantEntity", "Variant")
                        .WithMany("Prices")
                        .HasForeignKey("VariantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_price_snapshots_variants_variant_id");

                    b.Navigation("Variant");
                });

            modelBuilder.Entity("Skindexer.Api.Data.Entities.SkinVariantEntity", b =>
                {
                    b.HasOne("Skindexer.Api.Data.Entities.SkinItemEntity", "Item")
                        .WithMany("Variants")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_variants_items_item_id");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Skindexer.Api.Data.Entities.CollectionEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Skindexer.Api.Data.Entities.RarityEntity", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Skindexer.Api.Data.Entities.RarityGroupEntity", b =>
                {
                    b.Navigation("Rarities");
                });

            modelBuilder.Entity("Skindexer.Api.Data.Entities.SkinItemEntity", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Skindexer.Api.Data.Entities.SkinVariantEntity", b =>
                {
                    b.Navigation("Prices");
                });
#pragma warning restore 612, 618
        }
    }
}
